using System;
using System.ComponentModel;
using Godot;
using Nebula.Serialization;
using Nebula.Serialization.Serializers;
using MongoDB.Bson;
using System.Threading.Tasks;

namespace Nebula
{
    /**
		<summary>
		<see cref="Node">Node</see>, extended with Nebula networking capabilities. This is the most basic networked object.
		On every network tick, all NetNode nodes in the scene tree automatically have their <see cref="NetProperty">network properties</see> updated with the latest data from the server.
		Then, the special <see cref="_NetworkProcess(int)">NetworkProcess</see> method is called, which indicates that a network Tick has occurred.
		Network properties can only update on the server side.
		For a client to update network properties, they must send client inputs to the server via implementing the <see cref="INetworkInputHandler"/> interface, or network function calls via <see cref="NetFunction"/> attributes.
		The server receives client inputs, can access them via <see cref="NetworkController.GetInput"/>, and handle them accordingly within <see cref="_NetworkProcess(int)">NetworkProcess</see> to mutate state.
		</summary>
	*/
    [Icon("res://addons/Nebula/Core/NetNode.png")]
    public partial class NetNode : Node, INetNode<NetNode>, INotifyPropertyChanged
    {
        public NetworkController Network { get; internal set; }
        public NetNode()
        {
            // Skip network initialization in editor to avoid errors during C# recompilation
            if (!Engine.IsEditorHint())
            {
                Network = new NetworkController(this);
            }
        }
        // Cannot have more than 8 serializers
        public IStateSerializer[] Serializers { get; private set; } = [];

        public override void _Notification(int what)
        {
            if (Engine.IsEditorHint()) return;
            if (what == NotificationSceneInstantiated)
            {
                Network.Setup();
            }
        }

        public virtual long InitializeInterest(NetPeer peer)
        {
            // By default, the peer has full interest in the node.
            return long.MaxValue;
        }

        public void SetupSerializers()
        {
            var spawnSerializer = new SpawnSerializer(Network);
            var propertySerializer = new NetPropertiesSerializer(Network);
            var interestResyncSerializer = new InterestResyncSerializer(Network);
            Serializers = [spawnSerializer, propertySerializer, interestResyncSerializer];
        }

        /// <summary>
        /// Test seam: installs hand-built serializers. SetupSerializers needs the Protocol
        /// registry (a registered net scene), which the Protocol-free unit fixtures don't have;
        /// this lets a WorldRunner-level test drive PeerAcknowledge against a recording
        /// serializer and a Protocol-free NetPropertiesSerializer.
        /// </summary>
        internal void SetSerializersForTests(IStateSerializer[] serializers)
        {
            Serializers = serializers;
        }

        public virtual void _WorldReady() { }
        public virtual void _NetworkProcess(int _tick) { }
        public virtual void _Despawn() { }

        /// <summary>
        /// Processes interpolation for all interpolated properties.
        /// Override is generated by the source generator for classes with [NetProperty(Interpolate = true)].
        /// </summary>
        /// <param name="delta">Frame delta time in seconds</param>
        internal virtual void ProcessInterpolation(float delta) { }

        /// <summary>
        /// Stores current predicted state for rollback comparison.
        /// Override is generated by the source generator for classes with [NetProperty(Predicted = true)].
        /// </summary>
        internal virtual void StorePredictedState(int tick) { }

        /// <summary>
        /// Stores confirmed server state for reconciliation.
        /// Override is generated by the source generator for classes with [NetProperty(Predicted = true)].
        /// </summary>
        internal virtual void StoreConfirmedState() { }

        /// <summary>
        /// Compares predicted state with confirmed server state and restores mispredicted properties.
        /// Returns true if any misprediction was detected (rollback needed), false if all predictions correct.
        /// If forceRestoreAll is true, skips comparison and restores all properties to confirmed state.
        /// Override is generated by the source generator for classes with [NetProperty(Predicted = true)].
        /// </summary>
        internal virtual bool Reconcile(int tick, bool forceRestoreAll = false) => false;

        /// <summary>
        /// Restores properties from the prediction buffer for a given tick.
        /// Used when prediction was correct and we need to continue with predicted values after server state import.
        /// Override is generated by the source generator for classes with [NetProperty(Predicted = true)].
        /// </summary>
        internal virtual void RestoreToPredictedState(int tick) { }

        /// <summary>
        #region Explicit Interface Implementations
        // These delegate to the internal virtual methods to enable proper polymorphic dispatch
        // when called through the INetNodeBase interface. Without these, the interface's default
        // implementations would be called instead of the overridden methods in derived classes.
        
        void INetNodeBase.StorePredictedState(int tick) => StorePredictedState(tick);
        void INetNodeBase.StoreConfirmedState() => StoreConfirmedState();
        bool INetNodeBase.Reconcile(int tick, bool forceRestoreAll) => Reconcile(tick, forceRestoreAll);
        void INetNodeBase.RestoreToPredictedState(int tick) => RestoreToPredictedState(tick);
        #endregion

        /// <summary>
        /// Sets a network property by its class-local index.
        /// Override is generated by the source generator for classes with [NetProperty] attributes.
        /// </summary>
        /// <param name="propIndex">The class-local property index</param>
        /// <param name="value">The new value from the network</param>
        internal virtual void SetNetPropertyByIndex(int propIndex, ref PropertyCache value) { }

        /// <summary>
        /// Invokes property change handlers for properties with NotifyOnChange = true.
        /// Override is generated by the source generator.
        /// </summary>
        internal virtual void InvokePropertyChangeHandler(int propIndex, int tick, ref PropertyCache oldVal, ref PropertyCache newVal) { }

        /// <summary>
        /// Seeds the network property cache for INetSerializable object properties initialized inline
        /// (inline init bypasses the setter). Called from _NetworkPrepare; the override is generated by
        /// the source generator for classes that have such properties.
        /// </summary>
        internal virtual void InitializeNetPropertyBindings() { }

        /// <summary>
        /// Writes all [NetProperty] values to a BSON document.
        /// Override is generated by the source generator for classes with [NetProperty] attributes.
        /// </summary>
        internal virtual void WriteBsonProperties(BsonDocument doc, NetBsonContext context = default) { }

        /// <summary>
        /// Reads [NetProperty] values from a BSON document.
        /// Override is generated by the source generator for classes with [NetProperty] attributes.
        /// </summary>
        internal virtual void ReadBsonProperties(BsonDocument doc) { }

        /// <summary>
        /// Invokes a network function by name with PropertyCache arguments.
        /// Override is generated by the source generator for classes with [NetFunction] methods.
        /// </summary>
        internal virtual void InvokeNetFunctionByName(string funcName, PropertyCache[] args) { }

        /// <inheritdoc/>
        public override void _Process(double delta)
        {
            // Guard against disposed objects (can happen during node removal)
            if (!IsInstanceValid(this)) return;
            base._Process(delta);
            // Process interpolation on clients only
            // Note: Don't iterate StaticNetworkChildren here - Godot calls _Process on each node,
            // so each node handles its own interpolation. Manual iteration causes double-processing.
            if (!Network.IsServer)
            {
                ProcessInterpolation((float)delta);
            }
        }

        /// <inheritdoc/>
        public override void _PhysicsProcess(double delta) { }

        public static bool NetworkSerialize(WorldRunner currentWorld, NetPeer peer, NetNode obj, NetBuffer buffer, int maxBytes)
        {
            // maxBytes is ignored - a node reference is always small.
            return Nebula.Utility.NetNodeCommon.TryWriteNodeReference(currentWorld, peer, obj, buffer);
        }

        public static void OnPeerAcknowledge(NetNode obj, UUID peerId, Tick tick)
        {
            // No-op: NetNode doesn't track per-peer state
        }

        public static void OnPeerDisconnected(NetNode obj, UUID peerId)
        {
            // No-op: NetNode doesn't track per-peer state
        }

        public static NetNode NetworkDeserialize(WorldRunner currentWorld, NetPeer peer, NetBuffer buffer, NetNode existing = null)
        {
            // Note: existing parameter ignored - NetNode deserialization is a lookup, not a create/update
            var networkID = NetReader.ReadUInt16(buffer);
            if (networkID == 0)
            {
                return null;
            }
            var staticChildId = NetReader.ReadByte(buffer);
            var node = currentWorld.GetNodeFromNetId(networkID)?.RawNode as NetNode;
            if (node == null)
            {
                return null;
            }
            if (staticChildId > 0)
            {
                node = node.GetNodeOrNull(Protocol.UnpackNode(node.SceneFilePath, staticChildId)) as NetNode;
            }
            return node;
        }

        public BsonValue BsonSerialize(NetBsonContext context)
        {
            var doc = new BsonDocument();
            if (Network.IsNetScene())
            {
                var netId = Network.NetId;
                doc["NetId"] = NetId.BsonSerialize(in netId);
            }
            else
            {
                var parentNetId = Network.NetParent.NetId;
                doc["NetId"] = NetId.BsonSerialize(in parentNetId);
                doc["StaticChildPath"] = Network.NetParent.RawNode.GetPathTo(this).ToString();
            }
            return doc;
        }

        public virtual async Task OnBsonDeserialize(NetBsonContext context, BsonDocument doc)
        {
            // Base implementation - no custom logic needed for NetNode
            // Derived classes should override this method
            await Task.CompletedTask;
        }

        public async Task<NetNode> BsonDeserialize(NetBsonContext context, byte[] bson)
        {
            return await BsonDeserialize(context, bson, this);
        }

        public static async Task<NetNode> BsonDeserialize(NetBsonContext context, byte[] bson, NetNode obj)
        {
            var data = BsonTransformer.DeserializeBsonValue<BsonDocument>(bson);
            if (data.IsBsonNull) return null;
            var doc = data.AsBsonDocument;
            var node = obj ?? new NetNode();

            // NetNode-specific deserialization logic
            node.Network._prepareNetId = NetId.BsonDeserialize(doc["NetId"]);
            if (doc.Contains("StaticChildPath"))
            {
                node.Network._prepareStaticChildPath = doc["StaticChildPath"].AsString;
            }

            // Call the virtual method for custom deserialization logic
            await node.OnBsonDeserialize(context, doc);

            return node;
        }

        public string NodePathFromNetScene()
        {
            if (Network.IsNetScene())
            {
                return GetPathTo(this);
            }

            return Network.NetParent.RawNode.GetPathTo(this);
        }
    }
}
