#!/usr/bin/env bash
#
# Rebuilds the vendored ENet bindings and native libraries from the ENet-CSharp
# submodule. Run this after moving the submodule to a new tag:
#
#   git -C ENet-CSharp fetch --tags && git -C ENet-CSharp checkout <tag>
#   addons/Nebula/native/build-natives.sh
#
# Library.Initialize() throws unless the managed version constant matches
# enet_linked_version(), so ENet.cs and the three natives must always be
# regenerated from the same tag.
#
# Requires clang (macOS) and a running Docker daemon (Linux + Windows).

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../../.." && pwd)"
src="$repo/ENet-CSharp/Source/Native"
managed="$repo/ENet-CSharp/Source/Managed/ENet.cs"

if [ ! -f "$src/enet.c" ]; then
	echo "ENet-CSharp submodule not checked out; run: git submodule update --init" >&2
	exit 1
fi

tag="$(git -C "$repo/ENet-CSharp" describe --tags --always)"
echo "Building ENet $tag"

echo "==> managed bindings"
{
	cat <<-EOF
	// <auto-generated>
	// Vendored verbatim from ENet-CSharp/Source/Managed/ENet.cs at tag $tag.
	// Regenerate with addons/Nebula/native/build-natives.sh - do not edit by hand.
	//
	// Upstream stopped publishing to NuGet after 2.4.8, so both these managed
	// bindings and the native libraries under addons/Nebula/native are built from
	// the ENet-CSharp submodule. Library.Initialize() compares the version constant
	// in this file against enet_linked_version(), so the managed bindings and the
	// natives must always be regenerated from the same tag.
	// </auto-generated>
	#pragma warning disable 1591

	EOF
	cat "$managed"
} > "$here/../ENet/ENet.cs"

echo "==> macOS (universal arm64 + x86_64)"
clang -O2 -shared -fPIC -DENET_DLL -arch arm64 -arch x86_64 -mmacosx-version-min=11.0 \
	-o "$here/osx/libenet.dylib" "$src/enet.c"

echo "==> Linux x64 and Windows x64 (via Docker)"
docker run --rm --platform linux/amd64 \
	-v "$src":/src:ro -v "$here":/out debian:bookworm bash -c '
		set -e
		apt-get update -qq
		apt-get install -y --no-install-recommends gcc libc6-dev mingw-w64 binutils >/dev/null
		gcc -O2 -shared -fPIC -o /out/linux-x64/libenet.so /src/enet.c
		x86_64-w64-mingw32-gcc -O2 -shared -DENET_DLL -o /out/win-x64/enet.dll /src/enet.c \
			-lwinmm -lws2_32 -static-libgcc
		strip --strip-unneeded /out/linux-x64/libenet.so
		x86_64-w64-mingw32-strip --strip-unneeded /out/win-x64/enet.dll
	'

echo "Done. Rebuilt from $tag:"
file "$here/osx/libenet.dylib" "$here/linux-x64/libenet.so" "$here/win-x64/enet.dll"
